UPDATE users SET hesi_staff_id='ID01Fp0qWr1FGn', hesi_real_name='齐璐' WHERE id=3; -- [realname] bi=齐璐 → hesi=齐璐
UPDATE users SET hesi_staff_id='ID01Fp0lr0g9Gv', hesi_real_name='周余英' WHERE id=8; -- [realname] bi=周余英 → hesi=周余英
UPDATE users SET hesi_staff_id='ID01Fp0gj5znuT', hesi_real_name='王馨慧' WHERE id=11; -- [realname] bi=王馨慧 → hesi=王馨慧
UPDATE users SET hesi_staff_id='ID01KCwmsEcsH5', hesi_real_name='李磊磊' WHERE id=20; -- [cellphone] bi=石榴 → hesi=李磊磊
UPDATE users SET hesi_staff_id='ID01Fp0f21pEL5', hesi_real_name='贾翔惠' WHERE id=21; -- [cellphone] bi=贾翔惠 → hesi=贾翔惠
UPDATE users SET hesi_staff_id='ID01Fp0rf2RYuz', hesi_real_name='胡敏' WHERE id=22; -- [cellphone] bi=胡敏 → hesi=胡敏
UPDATE users SET hesi_staff_id='ID01MuHSzPuLmf', hesi_real_name='付莉美' WHERE id=23; -- [cellphone] bi=付莉美 → hesi=付莉美
UPDATE users SET hesi_staff_id='ID01Fp0gj5uwtF', hesi_real_name='周甲鸿' WHERE id=24; -- [cellphone] bi=周甲鸿 → hesi=周甲鸿
UPDATE users SET hesi_staff_id='ID01RXk4WenY75', hesi_real_name='李古月' WHERE id=25; -- [cellphone] bi=李古月 → hesi=李古月
UPDATE users SET hesi_staff_id='ID01Fp0kuKYKS3', hesi_real_name='郑佳伟' WHERE id=26; -- [cellphone] bi=郑佳伟 → hesi=郑佳伟
UPDATE users SET hesi_staff_id='ID01Fp0f21lToX', hesi_real_name='马洋' WHERE id=27; -- [cellphone] bi=马洋 → hesi=马洋
UPDATE users SET hesi_staff_id='ID01KPNXZyc0Ev', hesi_real_name='邢荣荣' WHERE id=28; -- [cellphone] bi=蹄子 → hesi=邢荣荣
UPDATE users SET hesi_staff_id='ID01Fp0hT5aP9R', hesi_real_name='余嘉俊' WHERE id=29; -- [cellphone] bi=余嘉俊 → hesi=余嘉俊
UPDATE users SET hesi_staff_id='ID01LLT2awOBQj', hesi_real_name='张思雨' WHERE id=30; -- [cellphone] bi=小雨 → hesi=张思雨
UPDATE users SET hesi_staff_id='ID01Fp0lr0hMnB', hesi_real_name='蒋瑶' WHERE id=32; -- [cellphone] bi=蒋瑶 → hesi=蒋瑶
UPDATE users SET hesi_staff_id='ID01Fp0kuKYqTl', hesi_real_name='虞希' WHERE id=33; -- [cellphone] bi=虞希 → hesi=虞希
UPDATE users SET hesi_staff_id='ID01ScdqftTeh1', hesi_real_name='邢贝贝' WHERE id=34; -- [cellphone] bi=贝 → hesi=邢贝贝
UPDATE users SET hesi_staff_id='ID01Fp0lr0anoj', hesi_real_name='林智霖' WHERE id=35; -- [cellphone] bi=大lin → hesi=林智霖
UPDATE users SET hesi_staff_id='ID01Fp0lr0alNd', hesi_real_name='曾蓉儿' WHERE id=36; -- [cellphone] bi=曾蓉儿 → hesi=曾蓉儿
UPDATE users SET hesi_staff_id='ID01Fp0mU0eI91', hesi_real_name='李岳' WHERE id=37; -- [cellphone] bi=李岳 → hesi=李岳
UPDATE users SET hesi_staff_id='ID01Fp0nSy6x3h', hesi_real_name='李浩' WHERE id=38; -- [cellphone] bi=李浩 → hesi=李浩
UPDATE users SET hesi_staff_id='ID01Fp0f21ltPp', hesi_real_name='许思燕' WHERE id=39; -- [cellphone] bi=许思燕 → hesi=许思燕
UPDATE users SET hesi_staff_id='ID01Fp0mU0o7xl', hesi_real_name='罗加芸' WHERE id=40; -- [cellphone] bi=罗加芸 → hesi=罗加芸
UPDATE users SET hesi_staff_id='ID01Fp0mU0enmL', hesi_real_name='谢依群' WHERE id=41; -- [cellphone] bi=谢依群 → hesi=谢依群
UPDATE users SET hesi_staff_id='ID01Sky5FJEr3p', hesi_real_name='沈康翔' WHERE id=42; -- [cellphone] bi=沈康翔 → hesi=沈康翔
UPDATE users SET hesi_staff_id='ID01Fp0mU0fByn', hesi_real_name='王丽' WHERE id=43; -- [cellphone] bi=大乔 → hesi=王丽
UPDATE users SET hesi_staff_id='ID01Fp0mU0o3xB', hesi_real_name='张俊' WHERE id=44; -- [cellphone] bi=张俊 → hesi=张俊
UPDATE users SET hesi_staff_id='ID01QPASgydze7', hesi_real_name='王可新' WHERE id=45; -- [cellphone] bi=王可新 → hesi=王可新
UPDATE users SET hesi_staff_id='ID01Rb9DpjAPxB', hesi_real_name='王锖' WHERE id=46; -- [cellphone] bi=小样(Little Young) → hesi=王锖
UPDATE users SET hesi_staff_id='ID01Fp0mU0iZJB', hesi_real_name='苏安妮' WHERE id=47; -- [cellphone] bi=苏安妮 → hesi=苏安妮
UPDATE users SET hesi_staff_id='ID01Fp0mU0oyYv', hesi_real_name='聂煜轩' WHERE id=48; -- [cellphone] bi=一柯 → hesi=聂煜轩
UPDATE users SET hesi_staff_id='ID01I1wBXxCOqr', hesi_real_name='王炎' WHERE id=49; -- [cellphone] bi=夏天 → hesi=王炎
UPDATE users SET hesi_staff_id='ID_3KjPmjLqbn_', hesi_real_name='韩冉冉' WHERE id=50; -- [cellphone] bi=韩冉冉 → hesi=韩冉冉
UPDATE users SET hesi_staff_id='ID01Fp0gj5uEt9', hesi_real_name='骆青欣' WHERE id=51; -- [cellphone] bi=骆骆 → hesi=骆青欣
UPDATE users SET hesi_staff_id='ID01Fp0nSy1L5R', hesi_real_name='薛帅' WHERE id=52; -- [cellphone] bi=薛帅 → hesi=薛帅
UPDATE users SET hesi_staff_id='ID01HsFvZC8VOL', hesi_real_name='沈鑫楠' WHERE id=53; -- [cellphone] bi=小新 → hesi=沈鑫楠
UPDATE users SET hesi_staff_id='ID01Fp0fkz4bJt', hesi_real_name='汤琳琳' WHERE id=54; -- [cellphone] bi=二七 → hesi=汤琳琳
UPDATE users SET hesi_staff_id='ID01tMVTKcTujl', hesi_real_name='朱兰兰' WHERE id=55; -- [cellphone] bi=朱兰兰 → hesi=朱兰兰
UPDATE users SET hesi_staff_id='ID01Fp0kuLamV9', hesi_real_name='黄承欢' WHERE id=1; -- [manual] admin → 黄承欢
