-- YS 用友来料检验单 (质量管理/质量检验). 数据源 /yonbip/QMS_QIT/inspectorder/list (billnum=qms_incominspectorder_list)
-- 一行 = 一张检验单(表头). inspect_result: 1=合格 2=不合格(核心预警字段). 来料全是安徽香松供货, 此表不屏蔽香松。
CREATE TABLE IF NOT EXISTS ys_inspection (
  id BIGINT NOT NULL COMMENT '检验单id(YS主键, 19位long)',
  code VARCHAR(64) DEFAULT NULL COMMENT '检验单号',
  billtype VARCHAR(20) DEFAULT NULL COMMENT '单据类型',
  trantype_name VARCHAR(64) DEFAULT NULL COMMENT '交易类型名(来料检验)',
  inspect_date DATETIME DEFAULT NULL COMMENT '检验日期',
  pk_material_code VARCHAR(64) DEFAULT NULL COMMENT '物料编码',
  pk_material_name VARCHAR(255) DEFAULT NULL COMMENT '物料名称',
  pk_batchcode VARCHAR(128) DEFAULT NULL COMMENT '批次号',
  pk_outsupplier BIGINT DEFAULT NULL COMMENT '供应商id',
  pk_outsupplier_name VARCHAR(255) DEFAULT NULL COMMENT '供应商名称',
  pk_org_name VARCHAR(255) DEFAULT NULL COMMENT '质检组织',
  verifystate INT DEFAULT NULL COMMENT '单据状态 11开立/0待检/10检验完成/1审批中/2已审批/4已驳回',
  inspect_result VARCHAR(10) DEFAULT NULL COMMENT '检验结果 1合格/2不合格(核心)',
  pk_stockstatus_statusname VARCHAR(64) DEFAULT NULL COMMENT '库存状态名(合格/废品)',
  handle_type_name VARCHAR(64) DEFAULT NULL COMMENT '处理方式(合格/报废/拒收/退货)',
  inspectnum DECIMAL(18,4) DEFAULT NULL COMMENT '检验数',
  qnum DECIMAL(18,4) DEFAULT NULL COMMENT '合格数',
  nqnum DECIMAL(18,4) DEFAULT NULL COMMENT '不合格数',
  nnum DECIMAL(18,4) DEFAULT NULL COMMENT '不良数',
  qrate DECIMAL(10,4) DEFAULT NULL COMMENT '合格率(%)',
  manufacture_date DATETIME DEFAULT NULL COMMENT '生产日期',
  validity_date DATETIME DEFAULT NULL COMMENT '有效期',
  vsourcecode VARCHAR(64) DEFAULT NULL COMMENT '来源单号',
  create_time DATETIME DEFAULT NULL COMMENT 'YS创建时间',
  modify_time DATETIME DEFAULT NULL COMMENT 'YS修改时间',
  pubts VARCHAR(32) DEFAULT NULL COMMENT 'YS时间戳',
  raw_json JSON DEFAULT NULL COMMENT '检验单全字段原始JSON',
  synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '同步时间',
  PRIMARY KEY (id),
  KEY idx_inspect_date (inspect_date),
  KEY idx_result (inspect_result),
  KEY idx_supplier (pk_outsupplier_name),
  KEY idx_material (pk_material_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='YS来料检验单(质检预警数据源)';
