#!/usr/bin/env python
"""生成 yonsuite_fields.go - 完整 ysField 列表 (213 字段)"""
import pymysql, json, re
from collections import defaultdict

# 已知 type → getter 映射
TYPE_TO_GETTER = {
    'BIGINT': 'getInt64', 'INT': 'getInt',
    'DECIMAL': 'getFloat',
    'TINYINT(1)': 'getBool',
    'DATETIME': 'getTime', 'DATE': 'getTime',
    'JSON': 'getJSON',
}


def to_snake(s):
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', s)
    s = re.sub(r'([a-z\d])([A-Z])', r'\1_\2', s)
    return s.lower()


def col_to_getter(col_type):
    t = col_type.upper()
    if t.startswith('DECIMAL'):
        return 'getFloat'
    if t == 'TINYINT(1)':
        return 'getBool'
    if t in ('BIGINT', 'INT'):
        return TYPE_TO_GETTER[t]
    if t in ('DATETIME', 'DATE'):
        return 'getTime'
    if t == 'JSON':
        return 'getJSON'
    return 'getStr'  # VARCHAR/TEXT 等


def main():
    conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='Hch123456',
                           database='bi_dashboard', charset='utf8mb4')
    cur = conn.cursor()
    # 拿现有所有列 + 类型 (按位置序)
    cur.execute("""
        SELECT COLUMN_NAME, DATA_TYPE, COLUMN_TYPE
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA='bi_dashboard' AND TABLE_NAME='ys_purchase_orders'
        ORDER BY ORDINAL_POSITION
    """)
    cols = cur.fetchall()
    print(f'-- 总列数: {len(cols)}')

    # 排除元数据列 (不参与 upsert)
    skip = {'pk', 'created_at', 'updated_at', 'head_item_json', 'raw_json'}

    # 需要从 raw_json 反查 camelCase 原 key (snake → orig)
    # 用 to_snake 规则反查: 扫一条 raw_json, 建 snake → orig 字典
    cur.execute("SELECT raw_json FROM ys_purchase_orders WHERE raw_json IS NOT NULL")
    snake_to_orig = {}
    for (raw,) in cur.fetchall():
        if not raw:
            continue
        try:
            rec = json.loads(raw)
        except Exception:
            continue
        for orig in rec.keys():
            sn = to_snake(orig)
            if sn not in snake_to_orig:
                snake_to_orig[sn] = orig

    # 手动 override (raw_json 里始终为 null 或不出现的字段, 用代码原始 mapping)
    manual_overrides = {
        'product_default_album_id': 'productDefaultAlbumId',
        'total_send_qty': 'totalSendQty',
        'list_discount_tax_type': 'listdiscountTaxType',
        'receive_status': 'receiveStatus',
        'bmake_st_purinvoice': 'bmake_st_purinvoice',
        'bmake_st_purinvoice_red': 'bmake_st_purinvoice_red',
        'bmake_st_purinrecord': 'bmake_st_purinrecord',
    }

    field_defs = []
    missing_orig = []
    for snake, dtype, ctype in cols:
        if snake in skip:
            continue
        getter = col_to_getter(ctype)
        orig = snake_to_orig.get(snake) or manual_overrides.get(snake)
        if orig is None:
            missing_orig.append(snake)
            orig = snake  # last-resort fallback
        field_defs.append((snake, orig, getter))

    print(f'-- 业务字段数: {len(field_defs)}')
    print(f'-- 找不到原 camelCase 的字段 ({len(missing_orig)}): {missing_orig}')

    # 生成 Go 代码
    lines = []
    lines.append('// Code generated by gen_ys_go_fields.py - DO NOT EDIT')
    lines.append('// 完整 ys_purchase_orders 字段映射 (208 业务字段, 不含 pk/created_at/updated_at/raw_json/head_item_json)')
    lines.append('//')
    lines.append('// 修改字段: 1) ALTER TABLE 加列 2) 重跑 gen_ys_go_fields.py 3) go build')
    lines.append('package main')
    lines.append('')
    lines.append('// ysField 一个 (snake_name, json_key, getter) 三元组')
    lines.append('type ysField struct {')
    lines.append('\tcol    string                                              // SQL 列名 (snake_case)')
    lines.append('\tkey    string                                              // raw_json 原 key (camelCase)')
    lines.append('\tgetter func(map[string]interface{}, string) interface{} // 类型安全取值')
    lines.append('}')
    lines.append('')
    lines.append('// ysPurchaseFields 全字段定义 (按 information_schema 序), upsertRecord 动态构建 INSERT/UPDATE')
    lines.append('var ysPurchaseFields = []ysField{')
    for snake, orig, getter in field_defs:
        lines.append(f'\t{{"{snake}", "{orig}", {getter}}},')
    lines.append('}')

    out_path = r'C:\Users\Administrator\bi-dashboard\server\cmd\sync-yonsuite-purchase\fields.go'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'写入 {out_path} ({len(field_defs)} 字段)')


if __name__ == '__main__':
    main()
