CREATE TABLE IF NOT EXISTS ys_material_out (
  pk BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  `account_org` VARCHAR(128) DEFAULT NULL COMMENT '核算组织',
  `account_org_name` VARCHAR(64) DEFAULT NULL COMMENT '核算组织名称',
  `audit_date` DATETIME DEFAULT NULL COMMENT '日期',
  `audit_time` DATETIME DEFAULT NULL COMMENT '审核时间',
  `auditor` VARCHAR(64) DEFAULT NULL COMMENT '审核人',
  `bar_code` VARCHAR(128) DEFAULT NULL COMMENT '编码',
  `batchno` VARCHAR(128) DEFAULT NULL COMMENT '批次号',
  `bustype` VARCHAR(128) DEFAULT NULL COMMENT '交易类型id',
  `bustype_extend_attrs_json` VARCHAR(255) DEFAULT NULL COMMENT 'bustype_extend_attrs_json',
  `bustype_name` VARCHAR(64) DEFAULT NULL COMMENT '交易类型(委外发料/销售出库等)',
  `code` VARCHAR(128) DEFAULT NULL COMMENT '单据编号(CLCK 开头)',
  `contacts_pieces` DECIMAL(20,8) DEFAULT NULL COMMENT 'contactsPieces',
  `contacts_quantity` DECIMAL(20,8) DEFAULT NULL COMMENT 'contactsQuantity',
  `cost_accounting_method` INT DEFAULT NULL COMMENT 'costAccountingMethod',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `creator` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  `department` VARCHAR(128) DEFAULT NULL COMMENT 'department',
  `department_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `factory_fi_org` VARCHAR(128) DEFAULT NULL COMMENT 'factoryFiOrg',
  `factory_fi_org_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `factory_org` VARCHAR(128) DEFAULT NULL COMMENT 'factoryOrg',
  `factory_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `firstuplineno` DECIMAL(20,8) DEFAULT NULL COMMENT 'firstuplineno',
  `id` BIGINT DEFAULT NULL COMMENT '主表id',
  `impact_stock_timing` INT DEFAULT NULL COMMENT 'impactStockTiming',
  `inv_exch_rate` DECIMAL(20,8) DEFAULT NULL COMMENT '汇率/费率',
  `invaliddate` DATETIME DEFAULT NULL COMMENT 'invaliddate',
  `is_beginning` TINYINT(1) DEFAULT NULL COMMENT '是否标记',
  `is_wf_controlled` TINYINT(1) DEFAULT NULL COMMENT '是否标记',
  `is_wip` TINYINT(1) DEFAULT NULL COMMENT '是否标记',
  `lineno` DECIMAL(20,8) DEFAULT NULL COMMENT 'lineno',
  `mater_outs` JSON DEFAULT NULL COMMENT 'materOuts',
  `mater_outs_product_cp` BIGINT DEFAULT NULL COMMENT 'productCp',
  `mater_outs_unit` BIGINT DEFAULT NULL COMMENT 'unit',
  `material_out_define_character` JSON DEFAULT NULL COMMENT 'materialOutDefineCharacter',
  `material_out_define_character__id` VARCHAR(128) DEFAULT NULL COMMENT 'ID',
  `memo` VARCHAR(128) DEFAULT NULL COMMENT 'memo',
  `modifier` VARCHAR(64) DEFAULT NULL COMMENT '修改人',
  `modify_time` DATETIME DEFAULT NULL COMMENT '修改时间',
  `nat_currency_money_digit` INT DEFAULT NULL COMMENT '本币',
  `nat_currency_price_digit` INT DEFAULT NULL COMMENT '本币',
  `nat_money` DECIMAL(20,8) DEFAULT NULL COMMENT '本币',
  `nat_unit_price` DECIMAL(20,8) DEFAULT NULL COMMENT '本币',
  `operator` VARCHAR(128) DEFAULT NULL COMMENT 'operator',
  `operator_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `org` VARCHAR(128) DEFAULT NULL COMMENT 'org',
  `org_code` VARCHAR(64) DEFAULT NULL COMMENT '编码',
  `org_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `post_account_status` INT DEFAULT NULL COMMENT '状态',
  `post_account_version` INT DEFAULT NULL COMMENT 'postAccountVersion',
  `print_count` INT DEFAULT NULL COMMENT 'printCount',
  `producedate` DATETIME DEFAULT NULL COMMENT 'producedate',
  `product` BIGINT DEFAULT NULL COMMENT 'product',
  `product_c_code` VARCHAR(64) DEFAULT NULL COMMENT '物料编码',
  `product_c_name` VARCHAR(128) DEFAULT NULL COMMENT '物料名称',
  `product_model` VARCHAR(128) DEFAULT NULL COMMENT 'product_model',
  `product_model_description` VARCHAR(128) DEFAULT NULL COMMENT 'product_modelDescription',
  `product_unit_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `property_rights_transferred` TINYINT(1) DEFAULT NULL COMMENT 'propertyRightsTransferred',
  `pubts` DATETIME DEFAULT NULL COMMENT '时间戳',
  `qty` DECIMAL(20,8) DEFAULT NULL COMMENT 'qty',
  `recorddate` DATETIME DEFAULT NULL COMMENT 'recorddate',
  `source` VARCHAR(128) DEFAULT NULL COMMENT '源单据',
  `source_orderlineno` DECIMAL(20,8) DEFAULT NULL COMMENT '源单据',
  `src_bill_type` VARCHAR(128) DEFAULT NULL COMMENT 'srcBillType',
  `srcbill` VARCHAR(128) DEFAULT NULL COMMENT 'srcbill',
  `srcbillno` VARCHAR(128) DEFAULT NULL COMMENT 'srcbillno',
  `status` INT DEFAULT NULL COMMENT '状态',
  `stock_status_doc` BIGINT DEFAULT NULL COMMENT 'stockStatusDoc',
  `stock_status_doc_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `stock_unit_id` BIGINT DEFAULT NULL COMMENT 'ID',
  `stock_unit_id_precision` INT DEFAULT NULL COMMENT 'stockUnitId_Precision',
  `stock_unit_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `sub_qty` DECIMAL(20,8) DEFAULT NULL COMMENT 'subQty',
  `topsource` VARCHAR(128) DEFAULT NULL COMMENT 'topsource',
  `topupcode` VARCHAR(128) DEFAULT NULL COMMENT 'topupcode',
  `total_pieces` DECIMAL(20,8) DEFAULT NULL COMMENT 'totalPieces',
  `total_quantity` DECIMAL(20,8) DEFAULT NULL COMMENT 'totalQuantity',
  `unit_exchange_type` INT DEFAULT NULL COMMENT 'unitExchangeType',
  `unit_precision` INT DEFAULT NULL COMMENT 'unit_Precision',
  `unit_code` VARCHAR(64) DEFAULT NULL COMMENT '编码',
  `upcode` VARCHAR(128) DEFAULT NULL COMMENT '上游单据编号(委外入库单 WWRK)',
  `uplineno` DECIMAL(20,8) DEFAULT NULL COMMENT 'uplineno',
  `vendor` BIGINT DEFAULT NULL COMMENT 'vendor',
  `vendor_name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `verifystate` INT DEFAULT NULL COMMENT 'verifystate',
  `vouchdate` DATETIME DEFAULT NULL COMMENT '单据日期',
  `vouchtype` VARCHAR(64) DEFAULT NULL COMMENT 'vouchtype',
  `warehouse` BIGINT DEFAULT NULL COMMENT '仓库id',
  `warehouse_name` VARCHAR(128) DEFAULT NULL COMMENT '仓库名称',
  `write_off_enable` INT DEFAULT NULL COMMENT 'writeOffEnable',
  `write_off_status` INT DEFAULT NULL COMMENT '状态',
  raw_json JSON DEFAULT NULL COMMENT '完整 record 原始 JSON 备份',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_id (id),
  KEY idx_vouchdate (vouchdate),
  KEY idx_code (code),
  KEY idx_product_c_code (product_c_code),
  KEY idx_bustype (bustype)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='YS用友材料出库单(委外发料明细)';
