CREATE TABLE IF NOT EXISTS ys_stock (
  pk BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  `aimequipcard` DECIMAL(20,8) DEFAULT NULL COMMENT '目标设备卡',
  `applyorder` DECIMAL(20,8) DEFAULT NULL COMMENT '申请单量',
  `arrivalorder` DECIMAL(20,8) DEFAULT NULL COMMENT '到货订单量',
  `availableqty` DECIMAL(20,8) DEFAULT NULL COMMENT '⭐ 可用库存',
  `batchno` VARCHAR(128) DEFAULT NULL COMMENT '批次号',
  `currentqty` DECIMAL(20,8) DEFAULT NULL COMMENT '⭐ 当前库存',
  `custodian` INT DEFAULT NULL COMMENT '保管人',
  `custodian_type` VARCHAR(64) DEFAULT NULL COMMENT '保管人',
  `delivery` DECIMAL(20,8) DEFAULT NULL COMMENT '发货量',
  `id` BIGINT DEFAULT NULL COMMENT '现存量行 id (UK)',
  `innoticeqty` INT DEFAULT NULL COMMENT '到货预报',
  `inorderqty` INT DEFAULT NULL COMMENT '在订量',
  `invaliddate` DATETIME DEFAULT NULL COMMENT 'invaliddate',
  `inventoryowner` INT DEFAULT NULL COMMENT '存货所有者',
  `manage_class` BIGINT DEFAULT NULL COMMENT '管理类别 id',
  `manage_class_code` VARCHAR(64) DEFAULT NULL COMMENT '管理类别编码',
  `manage_class_name` VARCHAR(64) DEFAULT NULL COMMENT '管理类别名(易耗品/原料等)',
  `materialreq` DECIMAL(20,8) DEFAULT NULL COMMENT '材料需求',
  `morphologyconversionout` DECIMAL(20,8) DEFAULT NULL COMMENT '形态转换出',
  `org` VARCHAR(128) DEFAULT NULL COMMENT '组织 id',
  `org_code` VARCHAR(64) DEFAULT NULL COMMENT '组织编码',
  `org_name` VARCHAR(64) DEFAULT NULL COMMENT '组织名',
  `outnoticeqty` DECIMAL(20,8) DEFAULT NULL COMMENT '出库预报',
  `pickingreq` DECIMAL(20,8) DEFAULT NULL COMMENT '领料需求',
  `planavailableqty` DECIMAL(20,8) DEFAULT NULL COMMENT '计划可用库存',
  `pofreport` DECIMAL(20,8) DEFAULT NULL COMMENT 'PO 反馈',
  `poin` DECIMAL(20,8) DEFAULT NULL COMMENT 'PO 入',
  `poout` DECIMAL(20,8) DEFAULT NULL COMMENT 'PO 出',
  `posubarrivalorder` DECIMAL(20,8) DEFAULT NULL COMMENT 'PO 子到货',
  `posubin` DECIMAL(20,8) DEFAULT NULL COMMENT 'PO 子入',
  `posubout` DECIMAL(20,8) DEFAULT NULL COMMENT 'PO 子出',
  `preretailqty` INT DEFAULT NULL COMMENT '预留零售',
  `producedate` DATETIME DEFAULT NULL COMMENT 'producedate',
  `product` BIGINT DEFAULT NULL COMMENT '物料 id',
  `product_code` VARCHAR(64) DEFAULT NULL COMMENT '物料编码 (关联 YS)',
  `product_model` VARCHAR(128) DEFAULT NULL COMMENT 'product_model',
  `product_model_description` VARCHAR(128) DEFAULT NULL COMMENT '物料规格说明',
  `product_name` VARCHAR(128) DEFAULT NULL COMMENT '物料名称',
  `product_unit_code` VARCHAR(64) DEFAULT NULL COMMENT '主单位编码',
  `product_unit_name` VARCHAR(64) DEFAULT NULL COMMENT '主单位名称',
  `productsku` BIGINT DEFAULT NULL COMMENT 'SKU id',
  `productsku_code` VARCHAR(64) DEFAULT NULL COMMENT 'productsku_code',
  `productsku_name` VARCHAR(128) DEFAULT NULL COMMENT 'productsku_name',
  `purchaseorder` DECIMAL(20,8) DEFAULT NULL COMMENT '采购订单量',
  `reserved_arrival` DECIMAL(20,8) DEFAULT NULL COMMENT '预留到货',
  `reserved_shipping` DECIMAL(20,8) DEFAULT NULL COMMENT '预留发货',
  `reserveid` INT DEFAULT NULL COMMENT '保留 id',
  `retail_trade` DECIMAL(20,8) DEFAULT NULL COMMENT '零售交易',
  `returnorder` DECIMAL(20,8) DEFAULT NULL COMMENT '退货单量',
  `salesorder` DECIMAL(20,8) DEFAULT NULL COMMENT '销售订单量',
  `sensitive_uid` VARCHAR(64) DEFAULT NULL COMMENT '敏感唯一标识',
  `status_type` VARCHAR(64) DEFAULT NULL COMMENT '状态类型',
  `stock_status_doc` BIGINT DEFAULT NULL COMMENT '库存状态 id',
  `stock_status_doc_code` VARCHAR(64) DEFAULT NULL COMMENT '库存状态编码',
  `stock_status_doc_status_name` VARCHAR(64) DEFAULT NULL COMMENT 'stockStatusDoc_statusName',
  `storenotice` DECIMAL(20,8) DEFAULT NULL COMMENT '入库通知',
  `tradedelivery` DECIMAL(20,8) DEFAULT NULL COMMENT '交易发货',
  `tradeorder` DECIMAL(20,8) DEFAULT NULL COMMENT '交易订单',
  `transferapplyin` DECIMAL(20,8) DEFAULT NULL COMMENT '调拨申请入',
  `transferapplyout` DECIMAL(20,8) DEFAULT NULL COMMENT '调拨申请出',
  `unit` BIGINT DEFAULT NULL COMMENT '主计量 id',
  `warehouse` BIGINT DEFAULT NULL COMMENT '仓库 id',
  `warehouse_code` VARCHAR(64) DEFAULT NULL COMMENT '仓库编码',
  `warehouse_name` VARCHAR(128) DEFAULT NULL COMMENT '仓库名',
  raw_json JSON DEFAULT NULL COMMENT '完整 record 备份',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_id (id),
  KEY idx_product_code (product_code),
  KEY idx_warehouse (warehouse),
  KEY idx_org (org)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='YS用友现存量(行级: product×warehouse×batchno×status)';
